apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "argocd-appgenerator.fullname" . }}-helm
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
  - git:
      repoURL: {{ .Values.repoURL }}
      revision: {{ .Values.targetRevision }}
      directories:
        {{- toYaml .Values.helmDirectories | nindent 8 }}
  template:
    metadata:
      name: '{{`{{path[1]}}-{{path[3]}}`}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        example: {{ include "argocd-appgenerator.fullname" . }}
    spec:
      project: {{ include "argocd-appgenerator.fullname" . }}
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}
        path: '{{`{{path}}`}}'
        helm:
          parameters:
            # These are passed as parameters to take precedence over
            # `values.yaml`, `valuesObject` and `values` definitions elsewhere
            - name: clusterDomainUrl
              value: {{ .Values.clusterDomainUrl }}
            - name: repoURL
              value: {{ .Values.repoURL }}
            - name: targetRevision
              value: {{ .Values.targetRevision }}
          values: |
            namespace: {{ .Release.Namespace }}
      destination:
        server: https://kubernetes.default.svc
