apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "argocd-appgenerator.fullname" . }}-kustomize
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
  - git:
      repoURL: {{ .Values.repoURL }}
      revision: {{ .Values.targetRevision }}
      directories:
        {{- toYaml .Values.kustomizeDirectories | nindent 8 }}
  template:
    metadata:
      name: '{{`{{path[1]}}-{{path[2]}}`}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        example: {{ include "argocd-appgenerator.fullname" . }}
    spec:
      project: {{ include "argocd-appgenerator.fullname" . }}
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}
        path: '{{`{{path}}`}}'
      destination:
        server: https://kubernetes.default.svc
